version: '3.1'

services:
  scheduler:
    volumes:
      - ./lpp/code:/usr/src/app/
  worker:
    volumes:
      - ./lpp/code:/usr/src/app/
  api:
    ports:
    - "${API_PORT}:${API_PORT}"
    volumes:
      - ./lpp/code:/usr/src/app
  frontend:
    volumes:
      - ./frontend/code:/usr/src/app
    command: "python index.py"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  mongo:
    volumes:
      - /data/lpp:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  redis:
    ports:
      - 6379:6379
